### ISSUE TITLE
unexpected token error with ruby 2.0.0

### ISSUE THREAD

**Issue by leventyalcin** [scalefactory/build-cloud#25]
Hi, 

I'm getting error given below. 

```
/Library/Ruby/Gems/2.0.0/gems/json-1.8.1/lib/json/common.rb:155:in `parse': 757: unexpected token at 'VPCS	xxx.xxx.xxx.xxx/xx	dopt-xxxxxxxxx	default	False	available	vpc-xxxxxxxx (JSON::ParserError)
'
	from /Library/Ruby/Gems/2.0.0/gems/json-1.8.1/lib/json/common.rb:155:in `parse'
	from ./bin/bc-create-app-env:174:in `<main>'
```

Ruby version is `ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]`
Here is the gem list if it helps; 
```
$ gem list

*** LOCAL GEMS ***

activesupport (4.1.5)
addressable (2.3.6)
bigdecimal (1.2.0)
blankslate (2.1.2.4)
buftok (0.2.0)
bundle (0.0.1)
bundler (1.6.2)
capistrano (3.2.1, 2.15.5)
capistrano-ext (1.2.1)
capybara (1.1.4)
celluloid (0.15.2)
celluloid-io (0.15.0)
CFPropertyList (2.2.8)
checkzilla (0.1.2)
childprocess (0.5.3)
clamp (0.6.3)
classifier (1.3.4)
coffee-script (2.2.0)
coffee-script-source (1.7.0)
colorator (0.1)
colorize (0.7.3)
digital_ocean (1.0.1)
equalizer (0.0.9)
eventmachine (1.0.3)
execjs (2.0.2)
facy (1.2.13)
faraday (0.9.0, 0.8.9)
faraday_middleware (0.9.1)
fast-stemmer (1.0.2)
ffi (1.9.3)
hashie (2.0.5)
highline (1.6.21)
hipchat (1.2.0)
http (0.6.1)
http_parser.rb (0.6.0)
httparty (0.13.1)
i18n (0.6.9)
io-console (0.4.2)
jekyll (2.0.2)
jekyll-coffeescript (1.0.0)
jekyll-sass-converter (1.0.0)
json (1.8.1, 1.7.7)
koala (1.10.0)
kramdown (1.3.3)
launchy (2.4.2)
libxml-ruby (2.6.0)
liquid (2.5.5)
listen (2.7.4)
magentify (0.0.7)
mail (2.6.1, 2.5.4)
memoizable (0.4.2)
mercenary (0.3.2)
middleware (0.1.0)
mime-types (2.3, 1.25.1, 1.21)
mini_portile (0.6.0)
minitest (5.4.1, 4.3.2)
multi_json (1.10.1)
multi_xml (0.5.5)
multipart-post (2.0.0, 1.2.0)
mustache (0.99.5)
naught (1.0.0)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (2.9.1)
net-ssh-gateway (1.2.0)
newrelic_rpm (3.6.7.159)
nio4r (1.0.0)
nokogiri (1.6.2.1, 1.5.6, 1.4.7)
open4 (1.3.4)
parslet (1.5.0)
polyglot (0.3.5)
pony (1.8)
posix-spawn (0.3.8)
psych (2.0.0)
pygments.rb (0.5.4)
rack (1.5.2)
rack-protection (1.5.3)
rack-test (0.6.2)
rake (10.1.1, 10.0.3, 0.9.6)
rash (0.4.0)
rb-fsevent (0.9.4)
rb-inotify (0.9.4)
rdoc (4.0.0)
redcarpet (3.1.1)
rmagick (2.13.3)
rubyzip (1.1.4)
safe_yaml (1.0.3)
sass (3.3.7)
selenium-webdriver (2.42.0)
simple_oauth (0.2.0)
sinatra (1.4.5)
sqlite3 (1.3.7)
sshkit (1.3.0)
talking-capistrano (0.1.9)
term-ansicolor (1.3.0)
test-unit (2.0.0.0)
thor (0.18.1)
thread_safe (0.3.4)
tilt (1.4.1)
timers (1.1.0)
tins (1.3.0)
tlsmail (0.0.1)
toml (0.1.1)
treetop (1.4.15)
tugboat (0.2.0)
twitter (5.9.0)
tzinfo (1.2.2)
websocket (1.0.7)
xpath (0.1.4)
yajl-ruby (1.1.0)
```

I've installed (just for testing) Same error with `ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]`

**Comment by jtopper** [comment]
Hi Levent,

I've been working on build-cloud a bit this week, but I haven't seen this error, so I'm wondering if it's specific to your config.  Can you tell me whether this is still happening for you, and if so, drop me an email with the real commandline you're using so that I can try it against your config?

**Comment by mikesilky** [comment]
Levent - also, as it looks like you're using our (non-open-source) wrappers around build-cloud, please can you run that wrapper script with --debug and give us the full build-cloud command line that's causing the error?

**Comment by mikemead** [comment]
I think this error was caused by the AWS cli used in the wrapper scripts not returning JSON if your default configuration said otherwise. If so, this has now been fixed.

**Comment by leventyalcin** [comment]
@mikemead merged my changes a while ago and it is ok right now 

```diff
- JSON.parse(`aws ec2 describe-instances --filters...
+ JSON.parse(`aws ec2 describe-instances --output json --filters...
```
